version: "3.7"

services:
  api:
    build: .
    expose:
      - 8000
    ports:
      - 8000:8000

  web:
      build: nginx
      ports:
        - 80:80
        - 443:443
      depends_on:
        - api